apiVersion: v1
kind: Service
metadata:
  name: {{ template "microservice.fullname" . }}
  labels:
    app: {{ template "microservice.name" . }}
    chart: {{ template "microservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "microservice.name" . }}
    release: {{ .Release.Name }}