# Default values for microservice.

replicaCount: 1
image:
  repository: 
  tag: 
  #image repo and tag set by CD pipeline

service:
  enabled: true
  type: ClusterIP
  httpPort: 80
  externalPort: 80

resources:
  limits:
    cpu: 400m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 64Mi


